name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    defaults:
      run:
        working-directory: final_project

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: |
          npx prisma generate
          npx prisma db push

      - name: Run unit tests (Jest)
        run: npm test

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: final_project
          start: npm run dev
          wait-on: http://localhost:3000
